config/routes.rb
Rails.application.routes.draw do
  resources :templates
  resources :items

  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
	belongs_to :template
end

app/models/template.rb
class Template < ApplicationRecord
	has_many :items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

	def new
		@item = Item.new
	end

	def create
	end

end

app/controllers/templates_controller.rb
class TemplatesController < ApplicationController

	def new
		@template = Template.new
		@item = Item.new
  end


	def create
	  @template = Template.new(params.require(:template).permit(:name))
	 
	  @template.save
	  redirect_to root_path
	end


private
  def template_params
    params.require(:template).permit(:name)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/templates_helper.rb
module TemplatesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app>
  <head>
    <title>Packrat</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application', controller_name %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/templates/new.html.slim
h2 Create a new template

div ng-controller="TemplateCtrl"
	<h1>{{ title }}</h1>

= form_for @template, url: templates_path do |template| 
  p
  	| template name
    = template.text_field :name

    = fields_for @item do |item|
    	p
    		| item name
    		= item.text_field :name
  p
    = template.submit

app/views/welcome/index.html.slim
h1 welcome to packrat
h2 do you go places? hate packing? always forget your contact lens solution? packrat is here to help.

button create a trip
button
	= link_to 'create template', new_template_path
button see all templates